version: '3'
services:

  jenkins.docker:
    image: shimmi/jenkins  #jenkinsci/blueocean
    container_name: docker-jenkins
    ports:
      - '8080:8080'
      #- '50000:50000'
    #environment:
    #    LOG_LEVEL: debug
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    privileged: true
