version: '3'
services:

  jenkins:
    image: jenkinsci/blueocean
    container_name: docker-jenkins
    ports:
      - '8080:8080'
      #- '50000:50000'
    #environment:
    #    LOG_LEVEL: debug
    volumes:
      - ./jenkins_home:/var/jenkins_home
